//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTLite.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CTLite.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the property &apos;{0}&apos;.
        /// </summary>
        internal static string CannotFindCompositeModelProperty {
            get {
                return ResourceManager.GetString("CannotFindCompositeModelProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The column name &apos;{0}&apos; is invalid.
        /// </summary>
        internal static string InvalidColumnName {
            get {
                return ResourceManager.GetString("InvalidColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the property &apos;{0}&apos;.
        /// </summary>
        internal static string InvalidPropertyName {
            get {
                return ResourceManager.GetString("InvalidPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The table name &apos;{0}&apos; is invalid.
        /// </summary>
        internal static string InvalidTableName {
            get {
                return ResourceManager.GetString("InvalidTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key [{0}] was not found.
        /// </summary>
        internal static string KeyNotFound {
            get {
                return ResourceManager.GetString("KeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composites must all be of the same type.
        /// </summary>
        internal static string MustAllBeSameCompositeType {
            get {
                return ResourceManager.GetString("MustAllBeSameCompositeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not have a CompositeModel attribute.
        /// </summary>
        internal static string MustHaveCompositeModelAttribute {
            get {
                return ResourceManager.GetString("MustHaveCompositeModelAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataContractAttribute missing from type &apos;{0}&apos;.
        /// </summary>
        internal static string MustHaveDataContractAttribute {
            get {
                return ResourceManager.GetString("MustHaveDataContractAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; must have a DataMemberAttribute.
        /// </summary>
        internal static string MustHaveDataMemberAttribute {
            get {
                return ResourceManager.GetString("MustHaveDataMemberAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeyPropertyAttribute missing from type &apos;{0}&apos;.
        /// </summary>
        internal static string MustHaveKeyPropertyAttribute {
            get {
                return ResourceManager.GetString("MustHaveKeyPropertyAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to keyPropertyValueGenerationFunc must return a unique key value.
        /// </summary>
        internal static string MustReturnAUniqueKeyValue {
            get {
                return ResourceManager.GetString("MustReturnAUniqueKeyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must supply a compositeContainerDictionaryPropertyName value.
        /// </summary>
        internal static string MustSupplyCompositeContainerDictionaryPropertyName {
            get {
                return ResourceManager.GetString("MustSupplyCompositeContainerDictionaryPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must supply an internalCompositeContainerDictionaryPropertyName value.
        /// </summary>
        internal static string MustSupplyInternalCompositeContainerDictionaryPropertyName {
            get {
                return ResourceManager.GetString("MustSupplyInternalCompositeContainerDictionaryPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must supply a modelDictionaryPropertyName value.
        /// </summary>
        internal static string MustSupplyModelDictionaryPropertyName {
            get {
                return ResourceManager.GetString("MustSupplyModelDictionaryPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must supply a modelFieldName value.
        /// </summary>
        internal static string MustSupplyModelFieldName {
            get {
                return ResourceManager.GetString("MustSupplyModelFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must supply a parentCompositePropertyName value.
        /// </summary>
        internal static string MustSupplyParentCompositePropertyName {
            get {
                return ResourceManager.GetString("MustSupplyParentCompositePropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must supply a parentPropertyName value.
        /// </summary>
        internal static string MustSupplyParentPropertyName {
            get {
                return ResourceManager.GetString("MustSupplyParentPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must supply a propertyName value.
        /// </summary>
        internal static string MustSupplyPropertyName {
            get {
                return ResourceManager.GetString("MustSupplyPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; must have a valid CompositeDictionaryPropertyAttribute.
        /// </summary>
        internal static string MustSupplyValidCompositeDictionaryPropertyAttribute {
            get {
                return ResourceManager.GetString("MustSupplyValidCompositeDictionaryPropertyAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; must have a valid ParentPropertyAttribute.
        /// </summary>
        internal static string MustSupplyValidParentPropertyAttribute {
            get {
                return ResourceManager.GetString("MustSupplyValidParentPropertyAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A placeholder path is required for the &apos;{0}&apos; value.
        /// </summary>
        internal static string PlaceholderPathRequiredError {
            get {
                return ResourceManager.GetString("PlaceholderPathRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The placeholder&apos;s type &apos;{0}&apos; must have a {1} that can convert from {2}.
        /// </summary>
        internal static string PlaceholderValueConversionError {
            get {
                return ResourceManager.GetString("PlaceholderValueConversionError", resourceCulture);
            }
        }
    }
}
